# Generated by Django 6.0.3 on 2026-03-03 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="resumes/")),
                ("extracted_text", models.TextField(blank=True)),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("tech", "Tech"),
                            ("commerce", "Commerce"),
                            ("marketing", "Marketing"),
                            ("engineering", "Engineering"),
                            ("healthcare", "Healthcare"),
                        ],
                        max_length=50,
                    ),
                ),
                ("matched_skills", models.TextField(blank=True, null=True)),
                ("missing_skills", models.TextField(blank=True, null=True)),
                ("score", models.FloatField(blank=True, null=True)),
                ("upload_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
